/**
 * Shipping-label sheet generation (browser-side).
 *
 * "Download the labels" has to produce a real file, so the copilot's `labels`
 * action is turned into a self-contained, print-styled HTML document and saved
 * through the same Blob route `exportToCsv` uses. HTML rather than PDF on
 * purpose: it prints 4x6 at full fidelity from any browser with no dependency,
 * and the demo stays dependency-free.
 */
import type { LabelOrder } from "@/lib/agent/actions";

const escape = (value: unknown) =>
  String(value ?? "").replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!,
  );

/**
 * A scannable-looking Code-128-ish barcode drawn with divs. It encodes nothing
 * a scanner would accept — it is a demo label — but it is derived from the
 * tracking number, so every label looks distinct and reprints look identical.
 */
function barcode(tracking: string): string {
  const bars: string[] = [];
  for (let i = 0; i < tracking.length; i++) {
    const code = tracking.charCodeAt(i);
    for (let bit = 0; bit < 4; bit++) {
      const wide = (code >> bit) & 1;
      bars.push(`<i style="width:${wide ? 3 : 1}px"></i><i class="g" style="width:${wide ? 1 : 2}px"></i>`);
    }
  }
  return `<div class="barcode">${bars.join("")}</div>`;
}

function labelCard(order: LabelOrder): string {
  return `
  <section class="label">
    <header>
      <span class="courier">${escape(order.courier)}</span>
      <span class="channel">${escape(order.marketplace)}</span>
    </header>
    <div class="to">
      <span class="tag">Deliver to</span>
      <strong>${escape(order.customer)}</strong>
      <span class="city">${escape(order.city)}</span>
    </div>
    <div class="meta">
      <div><span class="tag">Order</span><strong>${escape(order.number)}</strong></div>
      <div><span class="tag">Items</span><strong>${escape(order.itemCount)}</strong></div>
      <div><span class="tag">Value</span><strong>$${order.total.toFixed(2)}</strong></div>
    </div>
    ${barcode(order.tracking)}
    <footer>${escape(order.tracking)}</footer>
  </section>`;
}

/** The full printable document for a batch of labels. */
export function labelSheetHtml(orders: LabelOrder[]): string {
  const generated = new Date().toLocaleString("en-US");
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>ProSellerOS shipping labels (${orders.length})</title>
<style>
  * { box-sizing: border-box; }
  body { margin: 0; padding: 24px; background: #f4f4f5; font: 13px/1.4 ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; color: #18181b; }
  .toolbar { max-width: 880px; margin: 0 auto 20px; display: flex; align-items: center; gap: 12px; }
  .toolbar h1 { font-size: 15px; margin: 0; font-weight: 600; }
  .toolbar p { margin: 0; color: #71717a; font-size: 12px; }
  .toolbar button { margin-left: auto; border: 0; border-radius: 8px; background: #6366f1; color: #fff; padding: 8px 16px; font: inherit; font-weight: 600; cursor: pointer; }
  .sheet { max-width: 880px; margin: 0 auto; display: grid; grid-template-columns: repeat(auto-fill, minmax(288px, 1fr)); gap: 16px; }
  .label { background: #fff; border: 1px solid #d4d4d8; border-radius: 6px; padding: 14px; width: 100%; min-height: 384px; display: flex; flex-direction: column; }
  .label header { display: flex; align-items: baseline; border-bottom: 2px solid #18181b; padding-bottom: 8px; }
  .courier { font-size: 17px; font-weight: 700; letter-spacing: -0.02em; }
  .channel { margin-left: auto; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #71717a; }
  .tag { display: block; font-size: 9px; text-transform: uppercase; letter-spacing: 0.08em; color: #a1a1aa; }
  .to { padding: 14px 0; border-bottom: 1px dashed #d4d4d8; }
  .to strong { display: block; font-size: 19px; font-weight: 650; margin-top: 3px; }
  .city { font-size: 14px; color: #52525b; }
  .meta { display: flex; gap: 16px; padding: 12px 0; }
  .meta strong { font-size: 14px; font-variant-numeric: tabular-nums; }
  .barcode { margin-top: auto; display: flex; align-items: flex-end; height: 56px; overflow: hidden; }
  .barcode i { display: block; height: 100%; background: #18181b; }
  .barcode i.g { background: transparent; }
  .label footer { text-align: center; font-family: ui-monospace, "SFMono-Regular", monospace; font-size: 12px; letter-spacing: 0.14em; padding-top: 6px; }
  @media print {
    body { background: #fff; padding: 0; }
    .toolbar { display: none; }
    .sheet { display: block; max-width: none; }
    .label { border: 0; page-break-after: always; width: 4in; height: 6in; min-height: 0; }
  }
</style>
</head>
<body>
  <div class="toolbar">
    <div>
      <h1>${orders.length} shipping label${orders.length === 1 ? "" : "s"}</h1>
      <p>Generated by the ProSellerOS copilot &middot; ${escape(generated)} &middot; prints 4&times;6</p>
    </div>
    <button onclick="window.print()">Print all</button>
  </div>
  <div class="sheet">${orders.map(labelCard).join("")}</div>
</body>
</html>`;
}

/** Save the label sheet to the operator's downloads folder. */
export function downloadLabelSheet(orders: LabelOrder[]): void {
  const blob = new Blob([labelSheetHtml(orders)], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `proselleros-labels-${orders.length}.html`;
  link.click();
  URL.revokeObjectURL(url);
}
